main: si.lilbunnyrabbit.lilbot.lilBot
name: lilBot
version: 1.0
authors:
  - lilBunnyRabbit
description: lilBot plugin
commands:
  home:
    description: Teleport to your bed
    usage: /home
  spawn:
    description: Teleport to spawn
    usage: /spawn
  tpa:
    description: Teleport to player
    usage: /tpa <username>
  tpaccept:
    description: Accept teleport from player
    usage: /tpaccept
  tpdeny:
    description: Deny teleport from player
    usage: /tpdeny
  inventory:
    description: Show players inventory
    usage: /inventory <username>
  echest:
    description: Open your ender chest
    usage: /echest
  vanish:
    description: Hide from online players
    usage: /vanish
  uncover:
    description: Show yourself if you were hiding
    usage: /uncover
